### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by wesleycoder** [raulfdm/resume#2]
Sempre é bom ter um Readme.md no projeto descrevendo o que o projeto é por menor q ele seja.
É bom também colocar o link para o github pages q está on-line.
Assim quem encontrar o repositório pode facilmente visualizar o resultado.

**Comment by raulfdm** [comment]
Interessante. Vou escrever o Readme. Obrigado pela dica

**Comment by wesleycoder** [comment]
Não precisa fechar a issue agora assim, deixa pra fechar quando vc criar o Readme.
Vc pode fechar a issue direto do commit escrevendo Closes #2 na mensagem do commit.
